In [3]:
import torch
import torchvision
from pathlib import Path
import pandas as pd

In [4]:
device = torch.device("cpu")

RANDOM_SEED = torch.manual_seed(42)

In [17]:
BASE_DIR = Path.cwd().parent.parent

SPLIT_CSV_PATH = Path(BASE_DIR/'data', 'split.csv')

df = pd.read_csv(SPLIT_CSV_PATH)
df

               filepath category defect_type  split
0     test/good/000.png       OK        good  train
1     test/good/001.png       OK        good  train
2     test/good/002.png       OK        good  train
3     test/good/003.png       OK        good  train
4     test/good/004.png       OK        good   test
..                  ...      ...         ...    ...
475  train/good/315.png       OK        good  train
476  train/good/316.png       OK        good  train
477  train/good/317.png       OK        good  train
478  train/good/318.png       OK        good   test
479  train/good/319.png       OK        good  train

[480 rows x 4 columns]

In [21]:
df['new_filepath'] = df['filepath'].str.replace(
    r'^([^/]+)/([^/]+)/', r'\1_\2__', regex=True)

In [24]:
cols = ['new_filepath', 'category', 'defect_type']

train_manifest = df.loc[df['split']=='train'][cols]
val_manifest = df.loc[df['split']=='val'][cols]
test_manifest = df.loc[df['split']=='test'][cols]

In [26]:
train_manifest

            new_filepath category defect_type
0     test_good__000.png       OK        good
1     test_good__001.png       OK        good
2     test_good__002.png       OK        good
3     test_good__003.png       OK        good
5     test_good__005.png       OK        good
..                   ...      ...         ...
474  train_good__314.png       OK        good
475  train_good__315.png       OK        good
476  train_good__316.png       OK        good
477  train_good__317.png       OK        good
479  train_good__319.png       OK        good

[336 rows x 3 columns]